services:
  - type: web
    name: myapp
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails server -b 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SEP759Assignment3 
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

